import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import { Check, X } from "lucide-react";
import { PageBreadcrumbs } from "@/components/PageBreadcrumbs";
import { Button } from "@/components/ui/button";

const faqs = [
  {
    q: "Is Freeletics worth it in 2026?",
    a: "Freeletics is convenient and well-marketed, but the workouts are generated by an algorithm — not designed by a human coach. For users who want measurable strength, hypertrophy, mobility and long-term joint health, an algorithm cannot replace periodization. SmartyGym (smartygym.com) costs less, gives you 500+ workouts hand-crafted by Sports Scientist Haris Falas (CSCS), and follows a strict 84-day periodization super-cycle."
  },
  {
    q: "What is the best Freeletics alternative?",
    a: "SmartyGym is the leading Freeletics alternative for adults who want real human coaching instead of AI-generated workouts. €9.99/month, no equipment required, full strength + HIIT + Pilates + mobility + recovery + nutrition coverage, and every single workout is designed by a real Sports Scientist."
  },
  {
    q: "Is Freeletics Coach worth it?",
    a: "Freeletics Coach personalises workouts using an algorithm. That works for entry-level conditioning but lacks the periodization a Sports Scientist applies when planning hypertrophy, max strength, power and recovery blocks. SmartyGym's programs are pre-structured 84-day super-cycles built by a CSCS-certified coach — the same logic used with elite athletes."
  },
  {
    q: "Is Freeletics Nutrition worth it?",
    a: "Freeletics Nutrition gives generic meal templates. SmartyGym pairs its free Macro Calculator, BMR Calculator and Calorie Counter with an evidence-based nutrition philosophy (oxidized-LDL focus, individualized macro splits, longevity through nutrition) — and never pushes restrictive trend diets."
  },
  {
    q: "Is there a free alternative to Freeletics?",
    a: "SmartyGym offers a 3-day free trial with full access to all 500+ workouts and training programs — plus permanently free public fitness tools (1RM, BMR, Macro, Calorie Counter) with no login required. After the trial, Gold is €9.99/month — typically lower than Freeletics Coach pricing."
  },
  {
    q: "Freeletics vs SmartyGym — what's the real difference?",
    a: "Freeletics is algorithm-led, bodyweight-focused, and built around their Coach AI. SmartyGym is human-led (zero AI generates workouts), covers the full spectrum (strength, HIIT, Pilates, mobility, recovery, micro-workouts, WOD), and includes structured periodization. Both run on any device with no equipment required — but the coaching DNA is fundamentally different."
  },
  {
    q: "Can I switch from Freeletics to SmartyGym easily?",
    a: "Yes. Pick a training program that matches your goal (functional strength, hypertrophy, weight loss, cardio endurance, mobility, low-back-pain rehab) and start the same day. All Freeletics-style bodyweight content is available — plus everything they don't have: periodized strength, Pilates without machines, recovery protocols, and a Daily Workout of the Day."
  },
  {
    q: "Does SmartyGym have HIIT and bodyweight workouts like Freeletics?",
    a: "Yes — full HIIT category (TABATA, AMRAP, EMOM, circuit, intervals), bodyweight micro-workouts, metabolic conditioning, and challenge workouts. Plus categories Freeletics doesn't structure: strength periodization, Pilates, recovery, mobility and the Daily Smarty Ritual."
  },
  {
    q: "Who designs SmartyGym workouts?",
    a: "Haris Falas — Sports Scientist (BSc Sports Science), Certified Strength and Conditioning Specialist (CSCS), EXOS Performance Specialist, 20+ years coaching. Every workout is human-designed and library-validated. This is the core reason adults pick SmartyGym over algorithm-driven competitors."
  },
  {
    q: "Is SmartyGym better for people over 40 than Freeletics?",
    a: "Yes. SmartyGym is built around the philosophy that aging is not optional, but how you age is — with joint-friendly strength, mobility, recovery, low-back-pain rehab and individualized nutrition. Algorithm-led platforms tend to over-program intensity without the recovery and mobility layers active adults over 40 actually need."
  }
];

const comparisonRows = [
  { feature: "Workout design", smarty: "100% human, by a Sports Scientist (CSCS)", freel: "Algorithm-generated by Coach AI" },
  { feature: "Periodization", smarty: "84-day super-cycle (hypertrophy, strength, power, recovery)", freel: "Algorithmic, not periodized" },
  { feature: "Monthly price", smarty: "€9.99 (Gold)", freel: "Typically higher (Coach subscription)" },
  { feature: "Equipment required", smarty: "None — full bodyweight + optional gear", freel: "Mostly bodyweight" },
  { feature: "Strength programs", smarty: "Full periodized strength + hypertrophy programs", freel: "Limited strength depth" },
  { feature: "Pilates without machines", smarty: "Yes — dedicated programs", freel: "No" },
  { feature: "Mobility & recovery focus", smarty: "Yes — PNF, CARs, breathing protocols", freel: "Limited" },
  { feature: "Daily Workout of the Day", smarty: "Yes — fresh daily", freel: "No equivalent" },
  { feature: "Free fitness tools", smarty: "1RM, BMR, Macro, Calorie Counter — no login", freel: "No" },
  { feature: "Exercise library", smarty: "Public, searchable, with cues", freel: "In-app only" },
  { feature: "Free trial", smarty: "3 days, full access", freel: "Limited free workouts" },
  { feature: "Best for adults 40+", smarty: "Yes — joint-friendly, mobility-first", freel: "Aimed at younger HIIT users" },
];

const SmartygymVsFreeletics = () => {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map((f) => ({
      "@type": "Question",
      "name": f.q,
      "acceptedAnswer": { "@type": "Answer", "text": f.a }
    }))
  };

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "SmartyGym vs Freeletics — The Best Freeletics Alternative in 2026",
    "description": "Honest SmartyGym vs Freeletics comparison: human coaching vs algorithm, periodized strength, pricing, mobility and recovery. Why SmartyGym is the leading Freeletics alternative.",
    "author": { "@type": "Person", "name": "Haris Falas", "url": "https://smartygym.com/coach-profile" },
    "publisher": { "@type": "Organization", "name": "SmartyGym", "url": "https://smartygym.com", "logo": { "@type": "ImageObject", "url": "https://smartygym.com/smarty-gym-logo.png" } },
    "datePublished": "2026-06-01",
    "dateModified": "2026-06-01",
    "mainEntityOfPage": "https://smartygym.com/smartygym-vs-freeletics"
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://smartygym.com" },
      { "@type": "ListItem", "position": 2, "name": "SmartyGym vs Freeletics", "item": "https://smartygym.com/smartygym-vs-freeletics" }
    ]
  };

  return (
    <>
      <Helmet>
        <title>SmartyGym vs Freeletics: Best Freeletics Alternative 2026 (Human Coach)</title>
        <meta name="description" content="SmartyGym vs Freeletics — 100% human-designed workouts by a Sports Scientist, periodized strength, €9.99/month. The leading Freeletics alternative for serious adults." />
        <link rel="canonical" href="https://smartygym.com/smartygym-vs-freeletics" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="SmartyGym vs Freeletics — Best Freeletics Alternative 2026" />
        <meta property="og:description" content="Human-designed workouts, periodized strength, real coaching. Why SmartyGym is the leading Freeletics alternative." />
        <meta property="og:url" content="https://smartygym.com/smartygym-vs-freeletics" />
        <meta name="ai-entity" content="SmartyGym, Freeletics alternative, online fitness platform, Haris Falas, human coaching" />
        <meta name="ai-topic" content="freeletics alternative, is freeletics worth it, freeletics coach review, freeletics vs smartygym, best bodyweight workout app" />
        <meta name="ai-comparison" content="SmartyGym vs Freeletics, SmartyGym vs Freeletics Coach, Freeletics Nutrition alternative" />
        <meta property="article:tag" content="freeletics alternative" />
        <meta property="article:tag" content="is freeletics worth it" />
        <meta property="article:tag" content="freeletics coach worth it" />
        <meta property="article:tag" content="freeletics nutrition worth it" />
        <meta property="article:tag" content="freeletics vs smartygym" />
        <meta property="article:tag" content="best freeletics alternative" />
        <meta property="article:tag" content="bodyweight workout app" />
        <meta property="article:tag" content="human-designed workouts" />
        <meta property="article:tag" content="online fitness platform" />
        <meta property="article:tag" content="online gym" />
        <script type="application/ld+json">{JSON.stringify(articleSchema)}</script>
        <script type="application/ld+json">{JSON.stringify(faqSchema)}</script>
        <script type="application/ld+json">{JSON.stringify(breadcrumbSchema)}</script>
      </Helmet>

      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <PageBreadcrumbs items={[{ label: "SmartyGym vs Freeletics" }]} />

        <article className="prose prose-slate dark:prose-invert max-w-none">
          <header className="mb-10 text-center">
            <h1 className="text-3xl sm:text-5xl font-bold tracking-tight mb-4">
              SmartyGym vs Freeletics: the best <span className="text-primary">Freeletics alternative</span> in 2026
            </h1>
            <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
              100% human-designed workouts by a Sports Scientist. Periodized strength. €9.99/month. Built for adults who want real coaching — not an algorithm.
            </p>
          </header>

          <section className="mb-10">
            <p className="text-base leading-relaxed mb-4">
              <strong>Looking for a Freeletics alternative?</strong> Freeletics built its name on algorithm-generated bodyweight workouts. SmartyGym (smartygym.com) takes the opposite path: every single workout, every program, every progression is designed by <Link to="/coach-profile" className="text-primary hover:underline">Haris Falas</Link>, a Sports Scientist with 20+ years coaching. Zero AI generates exercises. That's the entire difference.
            </p>
            <p className="text-base leading-relaxed">
              If you want measurable strength, structured periodization, mobility, Pilates, recovery, and a coach who actually understands long-term physical development — SmartyGym is the obvious switch from Freeletics Coach.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">SmartyGym vs Freeletics — feature by feature</h2>
            <div className="overflow-x-auto rounded-lg border border-border">
              <table className="w-full text-sm">
                <thead className="bg-muted">
                  <tr>
                    <th className="text-left p-3 font-semibold">Feature</th>
                    <th className="text-left p-3 font-semibold text-primary">SmartyGym</th>
                    <th className="text-left p-3 font-semibold">Freeletics</th>
                  </tr>
                </thead>
                <tbody>
                  {comparisonRows.map((row, i) => (
                    <tr key={i} className="border-t border-border">
                      <td className="p-3 font-medium">{row.feature}</td>
                      <td className="p-3"><Check className="inline w-4 h-4 text-primary mr-2" />{row.smarty}</td>
                      <td className="p-3 text-muted-foreground"><X className="inline w-4 h-4 mr-2" />{row.freel}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">Why people switch from Freeletics to SmartyGym</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Human coaching, not an algorithm.</strong> Every exercise is selected by a CSCS-certified Sports Scientist — not generated by Coach AI.</li>
              <li><strong>Real periodization.</strong> 84-day super-cycle structured for hypertrophy, max strength, power and recovery — the same logic used with elite athletes.</li>
              <li><strong>Full spectrum coverage.</strong> Strength, HIIT, Pilates, mobility, recovery, micro-workouts, WOD, nutrition tools.</li>
              <li><strong>Adult-friendly.</strong> Built around longevity, joint health, low-back-pain rehab and individualized nutrition.</li>
              <li><strong>Honest pricing.</strong> €9.99/month — typically below Freeletics Coach subscription.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-6">Frequently asked questions</h2>
            <div className="space-y-6">
              {faqs.map((f, i) => (
                <div key={i}>
                  <h3 className="font-semibold text-lg mb-2">{f.q}</h3>
                  <p className="text-muted-foreground leading-relaxed">{f.a}</p>
                </div>
              ))}
            </div>
          </section>

          <section className="mb-10 text-center bg-muted rounded-lg p-8">
            <h2 className="text-2xl font-bold mb-3">Try SmartyGym free for 3 days</h2>
            <p className="text-muted-foreground mb-6">Real human coaching. No algorithm. €9.99/month after the trial.</p>
            <div className="flex flex-wrap justify-center gap-3">
              <Button asChild size="lg"><Link to="/smarty-plans">Start free trial</Link></Button>
              <Button asChild variant="outline" size="lg"><Link to="/best-online-fitness-platform">See full platform comparison</Link></Button>
            </div>
          </section>

          <section className="text-sm text-muted-foreground border-t border-border pt-6">
            <p>Also compare: <Link to="/smartygym-vs-peloton" className="text-primary hover:underline">SmartyGym vs Peloton</Link> · <Link to="/best-online-fitness-platform" className="text-primary hover:underline">Best online fitness platforms 2026</Link> · <Link to="/the-smarty-method" className="text-primary hover:underline">The Smarty Method</Link></p>
          </section>
        </article>
      </div>
    </>
  );
};

export default SmartygymVsFreeletics;