import { Helmet } from "react-helmet";
import { Card } from "@/components/ui/card";
import { FileText, UserCheck, CreditCard, Shield, AlertTriangle, Scale } from "lucide-react";
import { BackToTop } from "@/components/BackToTop";

const TermsOfService = () => {
  return (
    <>
      <Helmet>
        <title>Terms of Service | Smarty Gym</title>
        <meta name="description" content="Terms and Conditions for Smarty Gym. Read our terms of service for using our fitness programs and website." />
        <meta name="keywords" content="terms of service, terms and conditions, legal, Smarty Gym, Cyprus" />
      </Helmet>

      <div className="min-h-screen bg-background">
        <BackToTop />
        <div className="container mx-auto px-4 py-16 max-w-4xl">
          <div className="flex items-center gap-3 mb-8">
            <FileText className="h-10 w-10 text-primary" />
            <h1 className="text-4xl font-bold">Terms & Conditions</h1>
          </div>

          <Card className="p-8 space-y-8">
            <div className="prose dark:prose-invert max-w-none">
              <div className="bg-muted/50 p-4 rounded-lg mb-6">
                <p className="text-sm text-muted-foreground mb-2"><strong>Effective Date:</strong> August 15, 2025</p>
                <p className="text-sm text-muted-foreground mb-2"><strong>Website:</strong> www.smartygym.com</p>
                <p className="text-sm text-muted-foreground"><strong>Company:</strong> Smarty Gym</p>
              </div>

              <p className="text-lg text-muted-foreground">
                Welcome to Smarty Gym! By accessing or using our Website, services, and subscription-based fitness programs, 
                you agree to comply with and be bound by the following Terms & Conditions. Please read them carefully before 
                using our services.
              </p>

              <div className="flex items-start gap-3 mt-6">
                <UserCheck className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">1. Acceptance of Terms</h2>
                  <p className="text-muted-foreground">
                    By accessing or using Smarty Gym, you confirm that you have read, understood, and agree to these 
                    Terms & Conditions. If you do not agree, please do not use our Website or services.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <UserCheck className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">2. Eligibility</h2>
                  <p className="text-muted-foreground">
                    You must be at least 18 years old to use our services. By creating an account, you confirm that you 
                    are legally capable of entering into binding contracts under Cyprus and EU law.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <FileText className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">3. Services Provided</h2>
                  <p className="text-muted-foreground mb-3">
                    Smarty Gym provides online fitness programs, workout plans, and related digital content.
                  </p>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>Our programs are <strong>professionally designed by certified trainers</strong>, not generated by artificial intelligence.</li>
                    <li>The services are intended for <strong>personal fitness and wellness purposes only</strong> and are not a substitute for medical advice.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <UserCheck className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">4. Account Registration</h2>
                  <p className="text-muted-foreground mb-3">
                    To access certain features, you must create an account and provide accurate, complete, and up-to-date information.
                  </p>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>You are responsible for maintaining the confidentiality of your login details.</li>
                    <li>You agree not to share your account with others.</li>
                    <li>Any unauthorized use of your account must be reported immediately.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <CreditCard className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">5. Subscription & Payments</h2>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>Smarty Gym operates on a subscription model (e.g., monthly, yearly).</li>
                    <li>Payments are processed securely via third-party providers.</li>
                    <li>All fees are stated in Euros (€) and include VAT where applicable.</li>
                    <li>Subscriptions automatically renew unless cancelled prior to the renewal date.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <CreditCard className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">6. Cancellation & Refunds</h2>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>You may cancel your subscription anytime via your account settings.</li>
                    <li>No refunds will be provided for partial subscription periods.</li>
                    <li>If required by Cyprus consumer law, you may have a <strong>14-day right of withdrawal</strong> for digital services that have not yet started.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <AlertTriangle className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">7. Health Disclaimer</h2>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>All workouts and programs are designed for general fitness purposes.</li>
                    <li>Always consult a medical professional before beginning any new exercise program.</li>
                    <li>Smarty Gym is not responsible for injuries, health issues, or adverse effects resulting from misuse of our programs.</li>
                    <li>Participation is at your own risk.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <Shield className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">8. Intellectual Property</h2>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>All content on the Website (programs, videos, graphics, text, and logos) is the property of Smarty Gym.</li>
                    <li>Content may not be copied, distributed, or reproduced without prior written permission.</li>
                    <li>Users are granted a limited, personal, non-transferable license to access the content for personal use only.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <FileText className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">9. User Conduct</h2>
                  <p className="text-muted-foreground mb-3">You agree not to:</p>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>Misuse the Website or interfere with its functionality.</li>
                    <li>Share, sell, or distribute content without authorization.</li>
                    <li>Use the Website for unlawful or harmful activities.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <Shield className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">10. Limitation of Liability</h2>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>Smarty Gym provides fitness programs "as is" and makes no warranties regarding results.</li>
                    <li>To the maximum extent permitted by law, Smarty Gym shall not be liable for any direct, indirect, incidental, or consequential damages.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <Shield className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">11. Privacy & Data Protection</h2>
                  <p className="text-muted-foreground">
                    Your privacy is important to us. Please review our <strong>Privacy Policy</strong>, which explains 
                    how we collect, use, and protect your personal data in line with the <strong>GDPR</strong> and Cyprus law.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <FileText className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">12. Third-Party Services</h2>
                  <p className="text-muted-foreground">
                    Smarty Gym may integrate with third-party services (such as payment processors or video platforms). 
                    We are not responsible for their actions, policies, or services.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <FileText className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">13. Changes to Terms</h2>
                  <p className="text-muted-foreground">
                    Smarty Gym reserves the right to update or change these Terms & Conditions at any time. Updates will 
                    be posted on the Website with a revised effective date. Continued use of the Website constitutes 
                    acceptance of changes.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <Scale className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">14. Governing Law & Jurisdiction</h2>
                  <p className="text-muted-foreground mb-3">
                    These Terms & Conditions are governed by the laws of Cyprus and applicable EU regulations.
                  </p>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>Any disputes shall be subject to the exclusive jurisdiction of the courts of Cyprus.</li>
                  </ul>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <FileText className="h-6 w-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-bold mb-3">15. Contact Us</h2>
                  <p className="text-muted-foreground mb-3">
                    If you have questions about these Terms & Conditions, please contact us:
                  </p>
                  <p className="text-muted-foreground">
                    📩 Email: <a href="mailto:admin@smartygym.com" className="text-primary hover:underline">admin@smartygym.com</a>
                  </p>
                </div>
              </div>
            </div>
          </Card>

          <p className="text-center text-sm text-muted-foreground mt-8">
            Effective Date: August 15, 2025
          </p>
        </div>
      </div>
    </>
  );
};

export default TermsOfService;
