import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import { ScrollReveal } from "@/components/ScrollReveal";
import { PageBreadcrumbs } from "@/components/PageBreadcrumbs";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Shield, TrendingUp, Target, Heart, Clock,
  Dumbbell, CalendarDays, ListChecks, Sparkles, Wrench,
  BookOpen, Users, Newspaper, ClipboardList, Crown,
  ChevronRight, Award, Flame, Brain, Zap,
  BarChart3, CheckCircle2
} from "lucide-react";

const TheSmartyMethod = () => {
  const breadcrumbItems = [
    { label: "Home", href: "/" },
    { label: "The Smarty Method" },
  ];

  const periodizationPrinciples = [
    { icon: Shield, title: "Safety First", description: "Every movement is selected and sequenced to protect your body. Proper progression ensures you build strength without unnecessary risk." },
    { icon: TrendingUp, title: "Progressive Overload", description: "Structured increases in volume, intensity, and complexity ensure continuous adaptation and measurable improvement over time." },
    { icon: Target, title: "Performance Improvement", description: "Each training block has a clear objective. You always know what you're working toward and why." },
    { icon: Heart, title: "Injury Prevention", description: "Balanced programming addresses weaknesses, corrects imbalances, and includes recovery protocols to keep you training consistently." },
    { icon: Clock, title: "Long-Term Sustainability", description: "This is not a 30-day crash plan. It is a system designed to support your fitness for years, not weeks." },
  ];

  const workoutStructure = [
    { step: "01", title: "Clear Objective", description: "Every session starts with a defined goal — strength, calorie burning, metabolic conditioning, cardio, mobility and stability, challenge, pilates, recovery, or micro-workout." },
    { step: "02", title: "Warm-Up & Activation", description: "Targeted preparation that primes your muscles, joints, and nervous system for the work ahead." },
    { step: "03", title: "Primary Training Block", description: "The core of the session — structured sets, reps, and intensities aligned with the session's objective." },
    { step: "04", title: "Finisher Conditioning", description: "A focused finishing block designed to push capacity, burn calories, or reinforce the session's training effect." },
    { step: "05", title: "Cool-Down & Recovery", description: "Guided cool-down protocols to promote recovery, reduce soreness, and prepare your body for the next session." },
  ];

  const ecosystemItems = [
    { icon: CalendarDays, title: "Workout of the Day", description: "A fresh, professionally designed workout delivered daily. Structured, purposeful, and aligned with a periodized weekly plan — never random.", link: "/workout/wod", color: "text-primary" },
    { icon: Dumbbell, title: "Smarty Workouts", description: "Individual structured sessions across multiple categories — each with a clear focus, proper warm-up, primary training block, and cool-down.", link: "/workout", color: "text-primary" },
    { icon: ListChecks, title: "Smarty Programs", description: "Multi-week structured training plans with built-in progression. Designed to take you from where you are to where you want to be.", link: "/trainingprogram", color: "text-blue-500" },
    { icon: Sparkles, title: "Smarty Ritual", description: "Daily habits and routines that improve mindset, recovery, and consistency. The discipline behind the results.", link: "/daily-ritual", color: "text-purple-500" },
    { icon: Wrench, title: "Smarty Tools", description: "Performance tools — timers, 1RM calculators, BMR calculators, macro trackers — designed to support data-driven decisions.", link: "/tools", color: "text-orange-500" },
    { icon: BookOpen, title: "Exercise Library", description: "A curated, professional exercise database with proper demonstrations. Ensuring correct technique and movement quality.", link: "/exerciselibrary", color: "text-emerald-500" },
    { icon: Users, title: "Community", description: "A motivating digital environment where members support each other, share progress, and stay accountable.", link: "/community", color: "text-cyan-500" },
    { icon: Newspaper, title: "Blog", description: "Educational content focused on fitness, health, performance, and lifestyle optimization. Written by professionals, not generated by machines.", link: "/blog", color: "text-red-500" },
  ];

  const audienceSegments = [
    { icon: Dumbbell, title: "Home Athletes", description: "You prefer training from home and want professional, structured programming without guesswork." },
    { icon: Flame, title: "Busy Professionals", description: "Your schedule is demanding. You need effective, time-efficient workouts that deliver real results." },
    { icon: Brain, title: "Travelers", description: "You're on the move. SmartyGym travels with you — no equipment dependency, no excuses." },
    { icon: Zap, title: "Gym-Goers", description: "You go to the gym but want science-based programs designed by a real coach to guide your training." },
    { icon: Award, title: "Beginners", description: "You're starting your fitness journey and need safe, structured guidance from a qualified professional." },
    { icon: TrendingUp, title: "Experienced Lifters", description: "You've been training for years and want intelligent periodization to break through plateaus." },
  ];

  return (
    <>
      <Helmet>
        <title>The Smarty Method | SmartyGym Performance System</title>
        <meta name="description" content="Discover The Smarty Method — a complete performance system designed by Strength & Conditioning Coach Haris Falas. Science-based workouts, structured programs, and intelligent periodization." />
        <meta property="og:title" content="The Smarty Method | SmartyGym" />
        <meta property="og:description" content="More than workouts. A complete performance system built on science, experience, and intelligent periodization." />
        <meta property="og:type" content="website" />
        <link rel="canonical" href="https://smartygym.com/the-smarty-method" />
      </Helmet>

      <main className="min-h-screen bg-background">
        <div className="container mx-auto max-w-5xl px-4 py-8">
          <PageBreadcrumbs items={breadcrumbItems} />

          {/* Hero / Introduction */}
          <ScrollReveal>
            <section className="text-center mb-16">
              <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-6">
                More Than Workouts.{" "}
                <span className="text-primary">A Complete Performance System.</span>
              </h1>
              <p className="text-lg text-muted-foreground max-w-3xl mx-auto leading-relaxed">
                SmartyGym is not a collection of random workouts. It is a structured ecosystem designed by Strength and Conditioning Coach{" "}
                <Link to="/coach-profile" className="text-primary hover:underline font-semibold">Haris Falas</Link>,
                built on science, real-world coaching experience, and intelligent periodization.
                Every element serves a purpose. Every session has a goal. Every program follows a plan.
              </p>
            </section>
          </ScrollReveal>

          {/* The Expertise Behind the System */}
          <ScrollReveal delay={100}>
            <section className="mb-16">
              <Card className="border-primary/40">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex items-center gap-3 mb-4">
                    <Award className="w-7 h-7 text-primary flex-shrink-0" />
                    <h2 className="text-2xl sm:text-3xl font-bold">The Expertise Behind the System</h2>
                  </div>
                  <div className="space-y-4 text-muted-foreground leading-relaxed">
                    <p>
                      <Link to="/coach-profile" className="text-primary hover:underline font-semibold">Haris Falas</Link> is a qualified Strength and Conditioning Coach with a degree in Sports Science and years of hands-on experience in the fitness industry — from personal training and group coaching to program design and athlete preparation.
                    </p>
                    <p>
                      That experience shaped SmartyGym. Every workout, every program, every tool reflects a coaching philosophy rooted in <strong className="text-foreground">precision</strong>, <strong className="text-foreground">leadership</strong>, and <strong className="text-foreground">long-term thinking</strong>. This is not content created for clicks. It is training architecture designed for results.
                    </p>
                    <p>
                      The difference between a workout you found online and a workout from SmartyGym is the difference between guessing and knowing. When a professional designs your training, every variable is accounted for.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </section>
          </ScrollReveal>

          {/* Smart Periodization */}
          <ScrollReveal delay={100}>
            <section className="mb-16">
              <h2 className="text-2xl sm:text-3xl font-bold mb-2 text-center">Smart Periodization</h2>
              <p className="text-muted-foreground text-center mb-8 max-w-2xl mx-auto">
                Every workout and program is designed using structured periodization principles. This is not random programming. It is strategic and planned.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {periodizationPrinciples.map((item) => (
                  <Card key={item.title} className="border-primary/30 hover:border-primary transition-colors">
                    <CardContent className="p-5">
                      <div className="flex items-center gap-3 mb-3">
                        <item.icon className="w-5 h-5 text-primary flex-shrink-0" />
                        <h3 className="font-semibold text-lg">{item.title}</h3>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </section>
          </ScrollReveal>

          {/* How We Build Our Workouts */}
          <ScrollReveal delay={100}>
            <section className="mb-16">
              <h2 className="text-2xl sm:text-3xl font-bold mb-2 text-center">How We Build Our Workouts & Training Programs</h2>
              <p className="text-muted-foreground text-center mb-8 max-w-2xl mx-auto">
                Every session follows a deliberate structure. Nothing is left to chance.
              </p>
              <div className="space-y-4">
                {workoutStructure.map((item) => (
                  <Card key={item.step} className="border-primary/20 hover:border-primary/50 transition-colors">
                    <CardContent className="p-5 flex items-start gap-4">
                      <span className="text-2xl font-bold text-primary/40 flex-shrink-0 w-10">{item.step}</span>
                      <div>
                        <h3 className="font-semibold text-lg mb-1">{item.title}</h3>
                        <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </section>
          </ScrollReveal>

          {/* The Smarty Ecosystem */}
          <ScrollReveal delay={100}>
            <section className="mb-16">
              <h2 className="text-2xl sm:text-3xl font-bold mb-2 text-center">The Smarty Ecosystem</h2>
              <p className="text-muted-foreground text-center mb-8 max-w-2xl mx-auto">
                A complete, interconnected system where every component supports your progress.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {ecosystemItems.map((item) => (
                  <Link to={item.link} key={item.title} className="group">
                    <Card className="border-primary/20 hover:border-primary transition-all h-full group-hover:shadow-lg group-hover:shadow-primary/10">
                      <CardContent className="p-5">
                        <div className="flex items-center gap-3 mb-3">
                          <item.icon className={`w-5 h-5 flex-shrink-0 ${item.color}`} />
                          <h3 className="font-semibold text-lg">{item.title}</h3>
                          <ChevronRight className="w-4 h-4 ml-auto text-muted-foreground group-hover:text-primary transition-colors" />
                        </div>
                        <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
                      </CardContent>
                    </Card>
                  </Link>
                ))}
              </div>
            </section>
          </ScrollReveal>

          {/* The Logbook and Tracking System */}
          <ScrollReveal delay={100}>
            <section className="mb-16">
              <Card className="border-primary/40">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex items-center gap-3 mb-4">
                    <ClipboardList className="w-7 h-7 text-primary flex-shrink-0" />
                    <h2 className="text-2xl sm:text-3xl font-bold">The Logbook & Tracking System</h2>
                  </div>
                  <div className="space-y-4 text-muted-foreground leading-relaxed">
                    <p>
                      What gets measured gets managed. SmartyGym includes a built-in logbook and tracking system that allows you to record your workouts, monitor your progress, and review your history.
                    </p>
                    <p>
                      Track your <strong className="text-foreground">1RM progress</strong>, <strong className="text-foreground">BMR calculations</strong>, <strong className="text-foreground">macro targets</strong>, and <strong className="text-foreground">workout completions</strong>. Rate your sessions, leave notes, and build a complete training journal — all in one place.
                    </p>
                    <p>
                      Accountability creates consistency. Consistency creates results. The logbook is the bridge between effort and outcome.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </section>
          </ScrollReveal>

          {/* Two Smart Plans */}
          <ScrollReveal delay={100}>
            <section className="mb-16">
              <h2 className="text-2xl sm:text-3xl font-bold mb-2 text-center">Two Smart Plans</h2>
              <p className="text-muted-foreground text-center mb-8 max-w-2xl mx-auto">
                Full access to the entire SmartyGym ecosystem. Choose the commitment that fits your life.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 max-w-3xl mx-auto">
                <Card className="border-primary/30 hover:border-primary transition-colors">
                  <CardContent className="p-6 text-center">
                    <Crown className="w-8 h-8 text-primary mx-auto mb-3" />
                    <h3 className="text-xl font-bold mb-2">Monthly Plan</h3>
                    <p className="text-sm text-muted-foreground mb-4">
                      Full ecosystem access with the flexibility to manage your membership month to month. No long-term commitment required.
                    </p>
                    <Button asChild variant="outline" size="sm">
                      <Link to="/smarty-plans">View Plans</Link>
                    </Button>
                  </CardContent>
                </Card>
                <Card className="border-primary hover:shadow-lg hover:shadow-primary/10 transition-all">
                  <CardContent className="p-6 text-center">
                    <Crown className="w-8 h-8 text-primary mx-auto mb-3" />
                    <h3 className="text-xl font-bold mb-2">Yearly Plan</h3>
                    <p className="text-sm text-muted-foreground mb-4">
                      The same full access at the best value. Commit to a year of structured training and save. Serious results require serious commitment.
                    </p>
                    <Button asChild size="sm">
                      <Link to="/smarty-plans">View Plans</Link>
                    </Button>
                  </CardContent>
                </Card>
              </div>
            </section>
          </ScrollReveal>

          {/* Closing Section */}
          <ScrollReveal delay={100}>
            <section className="mb-8">
              <Card className="border-primary">
                <CardContent className="p-6 sm:p-10 text-center">
                  <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-4">
                    Built to Win. <span className="text-primary">Built to Last.</span>
                  </h2>
                  <p className="text-muted-foreground max-w-3xl mx-auto leading-relaxed mb-8">
                    SmartyGym is not a trend. It is not a 6-week challenge. It is a long-term performance system designed for people who want real, sustainable results. Every workout has a purpose. Every program follows a plan. Every tool supports your progress. This is what structured, professional fitness looks like.
                  </p>

                  <h3 className="text-xl font-bold mb-6">Who is SmartyGym For?</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 max-w-4xl mx-auto mb-8">
                    {audienceSegments.map((seg) => (
                      <div key={seg.title} className="flex items-start gap-3 p-4 bg-background/50 rounded-lg border border-primary/20 text-left">
                        <seg.icon className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                        <div>
                          <p className="font-semibold text-sm mb-1">{seg.title}</p>
                          <p className="text-xs text-muted-foreground leading-relaxed">{seg.description}</p>
                        </div>
                      </div>
                    ))}
                  </div>

                  <Button asChild size="lg">
                    <Link to="/smarty-plans">
                      <Crown className="mr-2 h-5 w-5" />
                      Start Your Journey
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            </section>
          </ScrollReveal>
        </div>
      </main>
    </>
  );
};

export default TheSmartyMethod;
