/**
 * Build-time pre-renderer.
 * Runs after `vite build` and writes real static HTML for every public
 * route, with unique <title>, <meta description>, canonical, OG tags, JSON-LD
 * and real crawlable body content inside <div id="root">.
 *
 * Google sees the static HTML on first response (no JavaScript required).
 * React's createRoot then hydrates and renders the live app on top.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, statSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSeoRoutes } from "./lib/seo-routes";
import {
  applyHeadOverrides,
  injectBody,
  injectJsonLd,
  renderRouteBody,
} from "./lib/seo-render";

const DIST = resolve("dist");
const TEMPLATE_PATH = join(DIST, "index.html");

function normalizeTemplate(html: string) {
  return html
    .replace(/<script\s+type=["']application\/ld\+json["']\s+data-prerender=["']1["']>[\s\S]*?<\/script>\s*/gi, "")
    .replace(/<div id="root">\s*<main[\s\S]*?<\/main>\s*<\/div>/i, '<div id="root"></div>');
}

function ensureParentDirectoryForFile(outPath: string) {
  const parentDir = dirname(outPath);
  if (existsSync(parentDir) && !statSync(parentDir).isDirectory()) {
    rmSync(parentDir, { force: true });
  }
  mkdirSync(parentDir, { recursive: true });
}

function isAncestorRoute(routePath: string, allPaths: Set<string>) {
  if (routePath === "/") return true;
  const prefix = `${routePath.replace(/\/$/, "")}/`;
  return [...allPaths].some((candidate) => candidate.startsWith(prefix));
}

function cleanUrlSourceFile(distDir: string, routePath: string, allPaths: Set<string>) {
  if (routePath === "/") return join(distDir, "index.html");
  const cleanPath = routePath.replace(/^\//, "");

  // Lovable's live host currently ignores generated _redirects rewrite rules
  // for deep SPA paths. Leaf routes therefore need to exist as exact files
  // (`dist/blog/article-slug`) so `curl /blog/article-slug` receives the
  // prerendered HTML before JavaScript. Parent routes keep index.html because
  // they must remain directories for their children.
  return isAncestorRoute(routePath, allPaths)
    ? join(distDir, cleanPath, "index.html")
    : join(distDir, cleanPath);
}

function redirectHtml(from: string, to: string) {
  const escapedTo = to.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
  return `<!doctype html>
<html lang="en-GB">
  <head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex, follow" />
    <meta http-equiv="refresh" content="0;url=${escapedTo}" />
    <link rel="canonical" href="https://smartygym.com${escapedTo}" />
    <title>Redirecting | SmartyGym</title>
  </head>
  <body>
    <p>Redirecting to <a href="${escapedTo}">${escapedTo}</a>.</p>
    <script>location.replace(${JSON.stringify(to)});</script>
  </body>
</html>`;
}

function writeCleanUrlRewrites(distDir: string, cleanPaths: string[], redirects: Array<{ from: string; to: string; status: 301 }> = []) {
  // Lovable's static host can serve the SPA fallback for clean URLs like
  // /blog/<slug> unless we explicitly point them at their generated folder
  // index files. Without these forced 200 rewrites, Googlebot can see the
  // homepage HTML for every article — wrong canonical, wrong content.
  const seen = new Set<string>();
  const rules: string[] = [];
  for (const rule of redirects.sort((a, b) => a.from.localeCompare(b.from))) {
    const key = `${rule.from}>${rule.to}`;
    if (seen.has(key) || rule.from === rule.to) continue;
    seen.add(key);
    rules.push(`${rule.from} ${rule.to} ${rule.status}!`);
    rules.push(`${rule.from}/ ${rule.to} ${rule.status}!`);
  }
  for (const p of [...cleanPaths].sort()) {
    if (seen.has(p)) continue;
    seen.add(p);
    rules.push(`${p} ${p} 200!`);
    rules.push(`${p}/ ${p} 200!`);
  }
  if (!rules.length) return;
  writeFileSync(
    join(distDir, "_redirects"),
    [
      "# Generated by scripts/prerender.ts",
      "# Maps every clean public URL to its prerendered .html file so Google",
      "# sees real per-page HTML (correct canonical, title, content) instead",
      "# of the SPA index.html fallback. The force marker protects these",
      "# SEO routes from any later SPA fallback rule on hosts that support it.",
      ...rules,
      "",
    ].join("\n"),
  );
}

export async function prerenderSeoHtml(options: {
  distDir?: string;
  templatePath?: string;
} = {}) {
  const distDir = options.distDir || DIST;
  const templatePath = options.templatePath || join(distDir, "index.html");

  if (!existsSync(templatePath)) {
    throw new Error(
      `[prerender] dist/index.html not found at ${templatePath}. Run after Vite writes the HTML bundle.`,
    );
  }
  const template = normalizeTemplate(readFileSync(templatePath, "utf8"));

  const { routes, redirects, counts } = await buildSeoRoutes();
  console.log(
    `[prerender] rendering ${counts.total} routes (` +
      `static=${counts.static}, workout-cat=${counts.workoutCategory}, ` +
      `program-cat=${counts.programCategory}, workouts=${counts.workouts}, ` +
      `programs=${counts.programs}, blog=${counts.blogArticles})`,
  );

  let written = 0;
  const writeHtml = (outPath: string, html: string) => {
    ensureParentDirectoryForFile(outPath);
    writeFileSync(outPath, html);
    written++;
  };

  const cleanPaths: string[] = [];
  const reportRows: string[] = [
    "# SmartyGym SEO prerender report",
    "",
    `Generated: ${new Date().toISOString()}`,
    `Routes: ${counts.total}`,
    "",
    "| URL | Static source file |",
    "| --- | --- |",
  ];
  for (const route of routes) {
    const { bodyHtml, jsonLd } = renderRouteBody(route);
    let html = applyHeadOverrides(template, route);
    html = injectJsonLd(html, jsonLd);
    html = injectBody(html, bodyHtml);

    if (route.path === "/") {
      writeHtml(join(distDir, "index.html"), html);
      reportRows.push("| / | dist/index.html |");
      continue;
    }

    const cleanPath = route.path.replace(/^\//, "");
    // Crawler-safe static output: the clean public URL `/foo/bar` maps to a
    // real static file at `dist/foo/bar/index.html`. We deliberately avoid
    // extensionless files (`dist/foo/bar`) because they conflict with this
    // directory pattern and were not reliable on the live host.
    const sourceFile = join(distDir, cleanPath, "index.html");
    writeHtml(sourceFile, html);
    reportRows.push(`| ${route.path} | ${sourceFile.replace(`${distDir}/`, "dist/")} |`);
    cleanPaths.push(route.path);
  }
  writeCleanUrlRewrites(distDir, cleanPaths, redirects);
  writeFileSync(join(distDir, "seo-prerender-report.md"), `${reportRows.join("\n")}\n`);
  console.log(`[prerender] wrote ${written} HTML files into ${distDir.replace(process.cwd() + "/", "")}/`);
}

async function main() {
  await prerenderSeoHtml();
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main().catch((err) => {
    console.error("[prerender] failed:", err);
    process.exit(1);
  });
}