/**
 * Build-time pre-renderer.
 * Runs after `vite build` and writes dist/<path>/index.html for every public
 * route, with unique <title>, <meta description>, canonical, OG tags, JSON-LD
 * and real crawlable body content inside <div id="root">.
 *
 * Google sees the static HTML on first response (no JavaScript required).
 * React's createRoot then hydrates and renders the live app on top.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSeoRoutes } from "./lib/seo-routes";
import {
  applyHeadOverrides,
  injectBody,
  injectJsonLd,
  renderRouteBody,
} from "./lib/seo-render";

const DIST = resolve("dist");
const TEMPLATE_PATH = join(DIST, "index.html");

function normalizeTemplate(html: string) {
  return html
    .replace(/<script\s+type=["']application\/ld\+json["']\s+data-prerender=["']1["']>[\s\S]*?<\/script>\s*/gi, "")
    .replace(/<div id="root">\s*<main[\s\S]*?<\/main>\s*<\/div>/i, '<div id="root"></div>');
}

function writeCleanUrlRewrites(distDir: string, cleanPaths: string[]) {
  // Lovable's static host serves the SPA fallback (index.html) for clean URLs
  // like /blog/<slug> unless we explicitly tell it to rewrite to the
  // prerendered .html file. Without these 200 rewrites, Googlebot sees the
  // homepage HTML for every article — wrong canonical, wrong content.
  const seen = new Set<string>();
  const rules: string[] = [];
  for (const p of [...cleanPaths].sort()) {
    if (seen.has(p)) continue;
    seen.add(p);
    rules.push(`${p} ${p}.html 200`);
    rules.push(`${p}/ ${p}.html 200`);
  }
  if (!rules.length) return;
  writeFileSync(
    join(distDir, "_redirects"),
    [
      "# Generated by scripts/prerender.ts",
      "# Maps every clean public URL to its prerendered .html file so Google",
      "# sees real per-page HTML (correct canonical, title, content) instead",
      "# of the SPA index.html fallback.",
      ...rules,
      "",
    ].join("\n"),
  );
}

export async function prerenderSeoHtml(options: {
  distDir?: string;
  templatePath?: string;
} = {}) {
  const distDir = options.distDir || DIST;
  const templatePath = options.templatePath || join(distDir, "index.html");

  if (!existsSync(templatePath)) {
    throw new Error(
      `[prerender] dist/index.html not found at ${templatePath}. Run after Vite writes the HTML bundle.`,
    );
  }
  const template = normalizeTemplate(readFileSync(templatePath, "utf8"));

  const { routes, counts } = await buildSeoRoutes();
  console.log(
    `[prerender] rendering ${counts.total} routes (` +
      `static=${counts.static}, workout-cat=${counts.workoutCategory}, ` +
      `program-cat=${counts.programCategory}, workouts=${counts.workouts}, ` +
      `programs=${counts.programs}, blog=${counts.blogArticles})`,
  );

  let written = 0;
  const writeHtml = (outPath: string, html: string) => {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, html);
    written++;
  };

  const cleanPaths: string[] = [];
  for (const route of routes) {
    const { bodyHtml, jsonLd } = renderRouteBody(route);
    let html = applyHeadOverrides(template, route);
    html = injectJsonLd(html, jsonLd);
    html = injectBody(html, bodyHtml);

    if (route.path === "/") {
      writeHtml(join(distDir, "index.html"), html);
      continue;
    }

    const cleanPath = route.path.replace(/^\//, "");
    // Always write the .html file. The _redirects rule maps the clean URL
    // (and trailing-slash variant) to this file with a 200 rewrite, so the
    // browser address bar keeps the clean URL while the host serves the
    // prerendered HTML. Canonical tags point to the clean URL.
    writeHtml(join(distDir, `${cleanPath}.html`), html);
    cleanPaths.push(route.path);
  }
  writeCleanUrlRewrites(distDir, cleanPaths);
  console.log(`[prerender] wrote ${written} HTML files into ${distDir.replace(process.cwd() + "/", "")}/`);
}

async function main() {
  await prerenderSeoHtml();
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main().catch((err) => {
    console.error("[prerender] failed:", err);
    process.exit(1);
  });
}